schema_version = "1.0.0"
id = "blender2ue_rig_exporter"
name = "Rig UE5 Exporter"
version = "0.0.3"
tagline = "Export rig to UE5"
maintainer = "Wiffzackius"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/WifiLast/blender2ue_rig_exporter"
copyright = [
    "2026 Martin St.",
]

[permissions]
files = "Export STL, PLY, OBJ files"
